import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:share_plus/share_plus.dart';

import '../../../../core/di/injection.dart';
import '../../../../core/constants/app_strings.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../../core/utils/extensions.dart';
import '../../../../shared/widgets/widgets.dart';
import '../../domain/entities/health_brief_entity.dart';
import '../bloc/health_brief_bloc.dart';

class BriefDetailPage extends StatefulWidget {
  final String briefId;

  const BriefDetailPage({super.key, required this.briefId});

  @override
  State<BriefDetailPage> createState() => _BriefDetailPageState();
}

class _BriefDetailPageState extends State<BriefDetailPage> {
  late HealthBriefBloc _bloc;
  bool _isSimpleView = true;

  @override
  void initState() {
    super.initState();
    _bloc = sl<HealthBriefBloc>();
    _bloc.add(HealthBriefLoadByIdRequested(widget.briefId));
  }

  void _onShare(HealthBriefEntity brief) {
    final shareText = '''
${brief.title}
${brief.reportDate.toDisplayDate()}${brief.labSource != null ? ' • ${brief.labSource}' : ''}

Summary:
${brief.geminiSummary}

Key Findings:
${brief.findings.map((f) => '• ${f.name}: ${f.value} ${f.unit} (${f.status.displayName})').join('\n')}

Questions for your appointment:
${brief.appointmentQuestions.asMap().entries.map((e) => '${e.key + 1}. ${e.value}').join('\n')}

Generated by MyHealth Brief
''';

    Share.share(shareText);
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(
      value: _bloc,
      child: Scaffold(
        backgroundColor: AppColors.background,
        appBar: AppBar(
          backgroundColor: AppColors.white,
          elevation: 0,
          leading: IconButton(
            icon: const FaIcon(FontAwesomeIcons.xmark),
            onPressed: () => context.pop(),
          ),
          title: const Text(AppStrings.briefGenerated),
          actions: [
            BlocBuilder<HealthBriefBloc, HealthBriefState>(
              builder: (context, state) {
                if (state is HealthBriefDetailLoaded) {
                  return IconButton(
                    icon: const FaIcon(FontAwesomeIcons.shareNodes),
                    onPressed: () => _onShare(state.brief),
                  );
                }
                return const SizedBox.shrink();
              },
            ),
          ],
        ),
        body: BlocBuilder<HealthBriefBloc, HealthBriefState>(
          builder: (context, state) {
            if (state is HealthBriefLoading) {
              return const Center(child: CircularProgressIndicator());
            }

            if (state is HealthBriefError) {
              return Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    FaIcon(
                      FontAwesomeIcons.circleExclamation,
                      size: 48,
                      color: AppColors.errorRed,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      state.message,
                      style: AppTextStyles.bodyMedium,
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 16),
                    ElevatedButton(
                      onPressed: () => _bloc.add(
                        HealthBriefLoadByIdRequested(widget.briefId),
                      ),
                      child: const Text(AppStrings.tryAgain),
                    ),
                  ],
                ),
              );
            }

            if (state is HealthBriefDetailLoaded) {
              return _buildContent(state.brief);
            }

            // Handle HealthBriefAnalyzed state (coming from analysis)
            if (state is HealthBriefAnalyzed) {
              return _buildContent(state.brief);
            }

            return const SizedBox.shrink();
          },
        ),
      ),
    );
  }

  Widget _buildContent(HealthBriefEntity brief) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Report Title
          Text(
            brief.title,
            style: AppTextStyles.h2,
          ),
          const SizedBox(height: 8),
          // Date and Lab
          Text(
            '${brief.reportDate.toDisplayDate()}${brief.labSource != null ? ' • ${brief.labSource}' : ''}',
            style: AppTextStyles.bodyMedium.copyWith(
              color: AppColors.textSecondary,
            ),
          ),
          const SizedBox(height: 20),
          // View Toggle
          ViewToggle(
            isSimpleView: _isSimpleView,
            onChanged: (isSimple) {
              setState(() {
                _isSimpleView = isSimple;
              });
            },
          ),
          const SizedBox(height: 24),
          // Gemini Summary
          GeminiSummaryCard(summary: brief.geminiSummary),
          const SizedBox(height: 24),
          // Detailed Findings
          Text(
            AppStrings.detailedFindings,
            style: AppTextStyles.h4,
          ),
          const SizedBox(height: 16),
          ...brief.findings.map(
            (finding) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: FindingCard(
                finding: finding,
                showClinicalDetails: !_isSimpleView,
              ),
            ),
          ),
          const SizedBox(height: 24),
          // Appointment Questions
          AppointmentQuestionsCard(
            questions: brief.appointmentQuestions,
          ),
          const SizedBox(height: 24),
          // AI Disclaimer
          const AiDisclaimerBanner(),
          const SizedBox(height: 32),
        ],
      ),
    );
  }
}
