// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWuQX8o4322mIwEkOKkEYNThNRK5oJE8Q',
    appId: '1:1008305903776:web:6e54bf9e717560890351c5',
    messagingSenderId: '1008305903776',
    projectId: 'myhealth-brief',
    authDomain: 'myhealth-brief.firebaseapp.com',
    storageBucket: 'myhealth-brief.firebasestorage.app',
    measurementId: 'G-VBW6NRNTC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN7qFCODDTQ72Sv4OIqzCbDOUnS4u8c_E',
    appId: '1:1008305903776:android:25f7c27ecc13f85c0351c5',
    messagingSenderId: '1008305903776',
    projectId: 'myhealth-brief',
    storageBucket: 'myhealth-brief.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9A5oRXBBN7bUUwjfQiRBXdufsW0sLESc',
    appId: '1:1008305903776:ios:a50e3cb9fe159cef0351c5',
    messagingSenderId: '1008305903776',
    projectId: 'myhealth-brief',
    storageBucket: 'myhealth-brief.firebasestorage.app',
    iosClientId: '1008305903776-tqimdapusmkurm17bm0323r6caqq0kgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myhealthBrief',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9A5oRXBBN7bUUwjfQiRBXdufsW0sLESc',
    appId: '1:1008305903776:ios:a50e3cb9fe159cef0351c5',
    messagingSenderId: '1008305903776',
    projectId: 'myhealth-brief',
    storageBucket: 'myhealth-brief.firebasestorage.app',
    iosClientId: '1008305903776-tqimdapusmkurm17bm0323r6caqq0kgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myhealthBrief',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWuQX8o4322mIwEkOKkEYNThNRK5oJE8Q',
    appId: '1:1008305903776:web:6c304c4de36996520351c5',
    messagingSenderId: '1008305903776',
    projectId: 'myhealth-brief',
    authDomain: 'myhealth-brief.firebaseapp.com',
    storageBucket: 'myhealth-brief.firebasestorage.app',
    measurementId: 'G-KNG2L8TGHC',
  );
}
