/// Application-wide constants
class AppConstants {
  AppConstants._();

  // App Info
  static const String appName = 'MyHealth Brief';
  static const String appVersion = '0.1.0';

  // Firebase Collections
  static const String usersCollection = 'users';
  static const String healthBriefsCollection = 'health_briefs';

  // Storage Paths
  static const String documentsStoragePath = 'documents';

  // Gemini
  static const String geminiModel = 'gemini-2.5-flash';

  // Timeouts
  static const Duration apiTimeout = Duration(seconds: 30);
  static const Duration geminiTimeout = Duration(seconds: 60);

  // Pagination
  static const int defaultPageSize = 20;

  // AI Disclaimer
  static const String aiDisclaimer =
      'This brief is generated by AI for informational purposes only. '
      'It is not a diagnosis. Always consult a qualified medical professional.';
}
